# Generated by Django 5.2.14 on 2026-05-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Form', 'verbose_name_plural': 'Contact Forms'},
        ),
        migrations.AlterModelOptions(
            name='homepagestats',
            options={'verbose_name': 'Homepage Statistics', 'verbose_name_plural': 'Homepage Statistics'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'News Image', 'verbose_name_plural': 'News Images'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
    ]
