# Generated by Django 5.2.14 on 2026-05-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contactform_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Form Submission', 'verbose_name_plural': 'Form Submissions'},
        ),
        migrations.AlterModelOptions(
            name='homepagestats',
            options={'verbose_name': 'Homepage data', 'verbose_name_plural': 'Homepage data'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News management'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Project management'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services Management'},
        ),
    ]
