# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contactform_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('cr_number', models.CharField(max_length=100)),
                ('est_year', models.CharField(max_length=20)),
                ('supplier_type', models.JSONField(default=list, help_text='Selected supplier types as a JSON list')),
                ('hq_address', models.TextField()),
                ('operates_libya', models.CharField(max_length=10)),
                ('cr_certificate', models.FileField(upload_to='supplier_registrations/cr_certificates/')),
                ('organisation_chart', models.FileField(upload_to='supplier_registrations/organisation_charts/')),
                ('company_profile', models.FileField(upload_to='supplier_registrations/company_profiles/')),
                ('fp_name', models.CharField(max_length=255)),
                ('fp_position', models.CharField(max_length=255)),
                ('fp_phone', models.CharField(max_length=50)),
                ('fp_email', models.EmailField(max_length=254)),
                ('tax_registration_certificate', models.FileField(upload_to='supplier_registrations/tax_certificates/')),
                ('vat_registration_certificate', models.FileField(blank=True, null=True, upload_to='supplier_registrations/vat_certificates/')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=100)),
                ('swift', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_address', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=50)),
                ('registration_type', models.JSONField(default=list, help_text='Selected registration types as a JSON list')),
                ('product_types', models.TextField()),
                ('warranty_terms', models.TextField()),
                ('support_info', models.TextField()),
                ('certs', models.JSONField(default=dict, help_text='Certification yes/no values keyed by certification name')),
                ('iso9001_certificate', models.FileField(blank=True, null=True, upload_to='supplier_registrations/certifications/')),
                ('iso14001_certificate', models.FileField(blank=True, null=True, upload_to='supplier_registrations/certifications/')),
                ('iso45001_certificate', models.FileField(blank=True, null=True, upload_to='supplier_registrations/certifications/')),
                ('apiq1_certificate', models.FileField(blank=True, null=True, upload_to='supplier_registrations/certifications/')),
                ('apiq2_certificate', models.FileField(blank=True, null=True, upload_to='supplier_registrations/certifications/')),
                ('lead_time', models.CharField(max_length=255)),
                ('export_ports', models.CharField(max_length=255)),
                ('logistics_address', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('representative', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Supplier Registration',
                'verbose_name_plural': 'Supplier Registration Management',
                'ordering': ['-created_at'],
            },
        ),
    ]
